version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: st_server_image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=den
      - POSTGRES_PASSWORD=12345


  stats-db:
    image: postgres:latest
    container_name: stats-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=den
      - POSTGRES_PASSWORD=12345

    # ewm-service:
    #  ports:
    #   - "8080:8080"

    #ewm-db:
    # image: postgres:14-alpine