version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: st_server_image
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=den
      - POSTGRES_PASSWORD=12345


  stats-db:
    image: postgres:latest
    container_name: stats-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=den
      - POSTGRES_PASSWORD=12345

  ewm-service:
    build: ./main
    image: ewm_service_image
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=den
      - POSTGRES_PASSWORD=12345

  ewm-db:
    image: postgres:latest
    container_name: ewm-postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=den
      - POSTGRES_PASSWORD=12345