DROP TABLE IF EXISTS stats;

CREATE TABLE IF NOT EXISTS stats
(
    id        BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(310)                NOT NULL,
    uri       VARCHAR(2048)               NOT NULL,
    ip        VARCHAR(45)                 NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);